from setuptools import setup, find_packages

setup(
    name='kineticsforge',
    version='2.0.0',
    description='Physics-constrained Neural ODE platform for battery diagnostics and material discovery',
    author='KineticsForge Team - Jadavpur University & IIT Madras',
    author_email='kineticsforge@example.com',
    url='https://github.com/Atin99/kineticsforge',
    packages=find_packages(),
    python_requires='>=3.9',
    install_requires=[
        'torch>=2.0.0',
        'numpy>=1.24.0',
        'scipy>=1.10.0',
        'scikit-learn>=1.2.2',
        'optuna>=3.2.0',
        'streamlit>=1.22.0',
        'plotly>=5.14.0',
        'matplotlib>=3.7.0',
        'pandas>=2.0.0',
        'pyarrow>=12.0.0',
        'pysindy>=1.7.5',
        'requests>=2.31.0',
        'beautifulsoup4>=4.12.0',
        'lxml>=4.9.0',
        'pdfplumber>=0.10.0',
        'h5py>=3.8.0',
        'pymatgen>=2023.3.10',
    ],
    extras_require={
        'gpu': ['torch-geometric>=2.3.0', 'torchdiffeq>=0.2.3'],
        'jax': ['jax>=0.4.10', 'jaxlib>=0.4.10', 'diffrax>=0.3.1'],
        'meta': ['learn2learn>=0.2.0'],
        'dev': ['pytest', 'black', 'flake8'],
    },
    entry_points={
        'console_scripts': [
            'kineticsforge-train=training.colab_kaggle.kaggle_colab_train:main',
            'kineticsforge-v2-readiness=validation.v2_readiness_report:main',
            'kineticsforge-kaggle-zip=training.colab_kaggle.kaggle_input_builder:main',
            'kineticsforge-data=data.hyper_data_pipeline:main',
            'kineticsforge-real=data.assemble_real_dataset:main',
            'kineticsforge-real-holdout=validation.real_holdout_benchmarks:main',
            'kineticsforge-full-cell=modules.full_cell.cell_architect:main',
            'kineticsforge-climate=core.regional_climate:main',
        ],
    },
    classifiers=[
        'Development Status :: 4 - Beta',
        'Intended Audience :: Science/Research',
        'Topic :: Scientific/Engineering :: Chemistry',
        'Programming Language :: Python :: 3.9',
    ],
)
